### ISSUE TITLE
Watch html not works

### ISSUE THREAD

**Issue by livsi** [LordFren/sassy-gulp#1]
Change /src/index.html - and not changed http://localhost:1337

**Comment by LordFren** [comment]
Would you be so kind and be more concise about the issue you are facing and give me more details, please.

**Comment by livsi** [comment]
gulp.watch(paths.styles[3], ["copyCode"], browserSync.reload); - this wrong in you gulpfile.js
gulp.watch(paths.code, ["copyCode"], browserSync.reload); - this work

**Comment by LordFren** [comment]
I just pushed a fix for it, can you verify it? Thank you for pointing it out for me! I derped a bit there!

**Comment by livsi** [comment]
Yes, it is work well
